export type Post = { id: string; author: string; role: string; time: string; body: string };
export type Thread = { id: string; title: string; description: string; posts: Post[] };
function post(
  id: number,
  author: string,
  role: string,
  day: number,
  hour: number,
  body: string,
): Post {
  return {
    id: `p${id}`,
    author,
    role,
    time: `2026-09-${String(day).padStart(2, "0")}T${String(hour).padStart(2, "0")}:00:00Z`,
    body,
  };
}
export const threads: Thread[] = [
  {
    id: "reversal",
    title: "How should preview recover after a restart?",
    description: "A decision, new evidence, and a change of direction.",
    posts: [
      post(
        1,
        "Maya Chen",
        "Engineering",
        15,
        9,
        "I propose persisting the preview session ID and reconnecting to that same session when the app restarts. It would make reopening a workspace feel instant. We would keep the last URL alongside the ID.",
      ),
      post(
        2,
        "Leo Martin",
        "Infrastructure",
        15,
        10,
        "One concern: preview session IDs belong to the server process. A desktop restart may also restart that process, leaving a saved ID pointing at something that no longer exists. Do we know how often that happens?",
      ),
      post(
        3,
        "Priya Shah",
        "Design",
        15,
        11,
        "The continuity sounds lovely. I like the direction! It would be nice to restore scroll position too.",
      ),
      post(
        4,
        "Maya Chen",
        "Engineering",
        15,
        13,
        "I checked ten local restarts with the server kept alive. All ten reconnected successfully. I have not tested a full machine restart or a new server process yet.",
      ),
      post(
        5,
        "Alex Rivera",
        "Project owner",
        15,
        15,
        "Decision for the experimental preview build: persist the session ID and last URL, and try to reconnect on desktop restart. Maya owns the implementation. This is limited to the experimental build until we check full restarts.",
      ),
      post(
        6,
        "Sam Brooks",
        "Support",
        16,
        9,
        "What should a person see while reconnecting? An indefinitely empty pane would look like data loss. We need a visible retry path.",
      ),
      post(
        7,
        "Priya Shah",
        "Design",
        16,
        10,
        "For that state, show “Reconnecting preview…” and a Start new preview button after five seconds. Alex, can we commit to that behavior?",
      ),
      post(
        8,
        "Alex Rivera",
        "Project owner",
        16,
        12,
        "Yes. We will show the reconnecting message and offer Start new preview after five seconds. Priya’s proposal is the accepted behavior for this experiment.",
      ),
      post(
        9,
        "Maya Chen",
        "Engineering",
        17,
        9,
        "Full restart test result: the server issues a new session token, so the saved ID can never reconnect. The desktop keeps polling the dead session. This reproduced on all three full restarts, even though the URL was still valid.",
      ),
      post(
        10,
        "Leo Martin",
        "Infrastructure",
        17,
        10,
        "That is the process-lifetime problem I raised. We can retain the last URL and scroll position, but should obtain a fresh session ID from the current server. Does this change the persistence decision?",
      ),
      post(
        11,
        "Alex Rivera",
        "Project owner",
        17,
        12,
        "Reversing Tuesday’s session-ID decision: do not restore a persisted preview session ID. Create a fresh session on restart, then reopen the saved URL. Keep the reconnecting message and retry button we agreed on. Maya will update the experimental implementation.",
      ),
      post(
        12,
        "Sam Brooks",
        "Support",
        17,
        13,
        "Thanks, that addresses the blank-state question. I still need an answer on whether the retry button is keyboard accessible before I can write the support note.",
      ),
    ],
  },
  {
    id: "no-decision",
    title: "Should preview tabs sync across devices?",
    description: "Plenty of enthusiasm. No commitment yet.",
    posts: [
      post(
        1,
        "Priya Shah",
        "Design",
        18,
        9,
        "Could we sync open preview tabs between a laptop and desktop? I imagine picking up the same workspace on another device without reopening everything.",
      ),
      post(
        2,
        "Sam Brooks",
        "Support",
        18,
        10,
        "A few people have asked for continuity between devices. It sounds useful to me.",
      ),
      post(
        3,
        "Maya Chen",
        "Engineering",
        18,
        11,
        "I like the idea. We would need to separate a workspace URL from the device-local session that serves it. I have not investigated the implementation.",
      ),
      post(
        4,
        "Leo Martin",
        "Infrastructure",
        18,
        13,
        "My concern is that preview URLs can point to localhost. A URL copied to another machine may identify an entirely different service. That needs a design before we commit.",
      ),
      post(
        5,
        "Alex Rivera",
        "Project owner",
        18,
        14,
        "Nice direction to explore. Please bring an example of cross-device behavior to our next design discussion. We have not decided to build tab sync or allocated anyone to implement it.",
      ),
      post(
        6,
        "Priya Shah",
        "Design",
        18,
        15,
        "That makes sense. I will collect examples for discussion. The product behavior is still open; this thread is not approval to implement synchronization.",
      ),
      post(
        7,
        "Sam Brooks",
        "Support",
        18,
        16,
        "Thanks everyone. Looking forward to seeing the exploration.",
      ),
    ],
  },
  {
    id: "resolved",
    title: "When should a cancelled import stop writing?",
    description: "A specific objection gets an explicit answer.",
    posts: [
      post(
        1,
        "Maya Chen",
        "Engineering",
        14,
        9,
        "Proposal: finish writing the current page after cancellation, then stop before requesting the next page. We can reuse the existing page receipt logic.",
      ),
      post(
        2,
        "Leo Martin",
        "Infrastructure",
        14,
        10,
        "I object to continuing the write after cancellation. The user might already have switched destinations, and that late write could land in the wrong project. Cancellation must be checked again before committing the page.",
      ),
      post(
        3,
        "Priya Shah",
        "Design",
        14,
        11,
        "Could the cancel button change to “Stopping…” until the current page settles? That might make the wait less surprising.",
      ),
      post(
        4,
        "Maya Chen",
        "Engineering",
        14,
        12,
        "I traced the write path. The project identity is captured at the start, but the transaction currently has no cancellation check. It is possible for a cancelled import to commit a page afterwards.",
      ),
      post(
        5,
        "Alex Rivera",
        "Project owner",
        14,
        14,
        "Decision: check the cancellation signal immediately before every page commit and roll back the uncommitted page if cancelled. This addresses Leo’s late-write concern. Keep the captured project identity. Maya will add a regression test for cancel-during-fetch.",
      ),
      post(
        6,
        "Leo Martin",
        "Infrastructure",
        14,
        15,
        "That resolves my objection: the cancelled page cannot be committed. Thanks for making the transaction boundary explicit.",
      ),
      post(
        7,
        "Priya Shah",
        "Design",
        14,
        16,
        "We still have not decided between immediately closing the progress panel and showing “Stopping…”. Can we decide the interface behavior separately?",
      ),
    ],
  },
];
